const messages=['Waking the bamboo forest','Loading Panda Man energy','Calibrating the fun meter','Almost ready for adventure'];
const pageLinks=[['Home','/'],['About','/about.html'],['Adventures','/adventures.html'],['Games','/games.html'],['Projects','/projects.html'],['Now','/now.html'],['Updates','/updates.html'],['Journal','/journal.html'],['Gallery','/gallery.html'],['Media','/media.html'],['Videos','/videos.html'],['Music','/music.html'],['Playlist','/playlist.html'],['Memes','/memes.html'],['Characters','/characters.html'],['Lore','/lore.html'],['Quests','/quests.html'],['Missions','/missions.html'],['Guides','/guides.html'],['Events','/events.html'],['Community','/community.html'],['Friends','/friends.html'],['Collabs','/collabs.html'],['Favorites','/favorites.html'],['Shoutouts','/shoutouts.html'],['Guestbook','/guestbook.html'],['Links','/links.html'],['Toolbox','/toolbox.html'],['Setup','/setup.html'],['Roadmap','/roadmap.html'],['Achievements','/achievements.html'],['Secrets','/secrets.html'],['Credits','/credits.html'],['FAQ','/faq.html'],['Contact','/contact.html'],['Start','/start.html']];
const currentPage=window.location.pathname.replace(/\/$/,'')||'/';
document.querySelectorAll('nav[aria-label="Main navigation"]').forEach(nav=>{nav.innerHTML=pageLinks.map(([label,href])=>`<a href="${href}"${href===currentPage?' aria-current="page"':''}>${label}</a>`).join('')});
const profilePicture='/panda.man420-avatar-1024.gif';
const loader=document.querySelector('#loader');
if(loader){
  const profileImage=loader.querySelector('.loader-mark img');
  if(profileImage){profileImage.src=profilePicture;profileImage.alt='Panda Man profile picture';}
}else{
  document.body.insertAdjacentHTML('afterbegin',`<div class="loader" id="loader" role="status" aria-label="Loading Panda Man site"><div class="loader-inner"><div class="loader-mark"><img src="${profilePicture}" alt="Panda Man profile picture"></div><div class="loader-copy"><span class="loader-label">Panda Man is loading</span><span class="loader-status">Bringing the good vibes online</span><span class="loader-bar" aria-hidden="true"><span></span></span></div></div></div>`);
}
window.addEventListener('load',()=>{const activeLoader=document.querySelector('#loader');const status=document.querySelector('.loader-status');let i=0;if(status){setInterval(()=>{i=(i+1)%messages.length;status.textContent=messages[i]},850)}if(activeLoader){setTimeout(()=>activeLoader.classList.add('is-hidden'),3600)}});
document.querySelector('#contact-form')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const subject=encodeURIComponent(`Message from ${data.get('name')}`);const body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\n\n${data.get('message')}`);window.location.href=`mailto:pandamanofficial420@gmail.com?subject=${subject}&body=${body}`;document.querySelector('#success')?.classList.add('visible')});
